[build]
builder = "nixpacks"
buildCommand = "npx vite build"

[deploy]
startCommand = "npx vite preview --port ${PORT:-8080}"

[variables]
NODE_VERSION = "18"
NIXPACKS_NO_TSC = "1"
NIXPACKS_NO_PINET = "1"

[phases]
install = "npm ci"