[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run railway-start"

[variables]
NODE_VERSION = "18"
NIXPACKS_NO_TSC = "1"
NIXPACKS_NO_PINET = "1"

[phases]
install = "npm ci"
build = "echo 'Skipping build phase - will build on start'"